using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.Extensions.Logging;

namespace Application.Services
{
    /// <summary>
    /// Service for calculating points in a league based on session finishing places.
    /// </summary>
    public class PointsService
    {
        /// <summary>
        /// List of points assigned to each place value in the bubble, keyed by the number of total
        /// participants.
        /// </summary>
        private static readonly Dictionary<int, List<int>> Points =
            new Dictionary<int, List<int>>
            {
                [10] = new List<int>
                {
                    10,
                    6,
                    4,
                },
                [20] = new List<int>
                {
                    16,
                    11,
                    8,
                    5,
                },
                [30] = new List<int>
                {
                    22,
                    16,
                    11,
                    6,
                    5,
                },
                [40] = new List<int>
                {
                    25,
                    19,
                    14,
                    10,
                    7,
                    5,
                },
                [50] = new List<int>
                {
                    28,
                    21,
                    15,
                    11,
                    8,
                    5,
                    4,
                    4,
                    4,
                },
                [60] = new List<int>
                {
                    32,
                    24,
                    18,
                    13,
                    9,
                    6,
                    5,
                    5,
                    4,
                    4,
                },
                [70] = new List<int>
                {
                    37,
                    28,
                    21,
                    15,
                    10,
                    7,
                    5,
                    5,
                    4,
                    4,
                    4,
                },
                [80] = new List<int>
                {
                    42,
                    30,
                    23,
                    17,
                    12,
                    8,
                    6,
                    5,
                    5,
                    4,
                    4,
                    4,
                },
                [90] = new List<int>
                {
                    45,
                    33,
                    25,
                    19,
                    14,
                    9,
                    7,
                    6,
                    5,
                    5,
                    4,
                    4,
                    4,
                },
                [100] = new List<int>
                {
                    47,
                    36,
                    27,
                    20,
                    15,
                    10,
                    8,
                    6,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                },
                [110] = new List<int>
                {
                    50,
                    38,
                    29,
                    21,
                    16,
                    12,
                    10,
                    8,
                    6,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [120] = new List<int>
                {
                    52,
                    40,
                    30,
                    22,
                    17,
                    13,
                    10,
                    8,
                    7,
                    6,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [130] = new List<int>
                {
                    54,
                    41,
                    32,
                    24,
                    19,
                    15,
                    12,
                    10,
                    8,
                    6,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [140] = new List<int>
                {
                    57,
                    43,
                    34,
                    26,
                    20,
                    16,
                    13,
                    11,
                    9,
                    7,
                    6,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [150] = new List<int>
                {
                    60,
                    46,
                    35,
                    28,
                    22,
                    17,
                    14,
                    12,
                    10,
                    8,
                    6,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [160] = new List<int>
                {
                    62,
                    47,
                    36,
                    29,
                    23,
                    18,
                    15,
                    12,
                    10,
                    8,
                    6,
                    6,
                    6,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [170] = new List<int>
                {
                    65,
                    49,
                    38,
                    31,
                    24,
                    20,
                    16,
                    13,
                    10,
                    8,
                    7,
                    6,
                    6,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [180] = new List<int>
                {
                    67,
                    50,
                    39,
                    32,
                    25,
                    21,
                    17,
                    13,
                    11,
                    9,
                    8,
                    7,
                    6,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [190] = new List<int>
                {
                    69,
                    51,
                    40,
                    33,
                    27,
                    22,
                    18,
                    15,
                    12,
                    10,
                    8,
                    7,
                    6,
                    6,
                    5,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [200] = new List<int>
                {
                    71,
                    53,
                    40,
                    35,
                    29,
                    24,
                    20,
                    16,
                    13,
                    10,
                    8,
                    7,
                    6,
                    6,
                    5,
                    5,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [210] = new List<int>
                {
                    73,
                    54,
                    41,
                    36,
                    30,
                    25,
                    21,
                    16,
                    13,
                    10,
                    8,
                    7,
                    6,
                    6,
                    5,
                    5,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [220] = new List<int>
                {
                    75,
                    56,
                    42,
                    37,
                    30,
                    25,
                    21,
                    17,
                    14,
                    11,
                    8,
                    7,
                    6,
                    6,
                    5,
                    5,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [230] = new List<int>
                {
                    76,
                    57,
                    43,
                    38,
                    31,
                    26,
                    22,
                    17,
                    14,
                    11,
                    9,
                    8,
                    6,
                    6,
                    5,
                    5,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [240] = new List<int>
                {
                    78,
                    58,
                    44,
                    39,
                    32,
                    26,
                    22,
                    18,
                    14,
                    11,
                    9,
                    8,
                    7,
                    7,
                    6,
                    6,
                    6,
                    6,
                    6,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [250] = new List<int>
                {
                    80,
                    60,
                    45,
                    39,
                    33,
                    27,
                    23,
                    18,
                    15,
                    11,
                    9,
                    8,
                    7,
                    7,
                    6,
                    6,
                    6,
                    6,
                    6,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                },
                [260] = new List<int>
                {
                    82,
                    61,
                    46,
                    40,
                    33,
                    28,
                    23,
                    18,
                    15,
                    12,
                    9,
                    8,
                    7,
                    7,
                    6,
                    6,
                    6,
                    6,
                    6,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [270] = new List<int>
                {
                    83,
                    62,
                    47,
                    41,
                    34,
                    28,
                    24,
                    19,
                    15,
                    12,
                    9,
                    8,
                    7,
                    7,
                    6,
                    6,
                    6,
                    6,
                    6,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [280] = new List<int>
                {
                    85,
                    64,
                    48,
                    42,
                    35,
                    29,
                    24,
                    19,
                    16,
                    12,
                    10,
                    8,
                    7,
                    7,
                    6,
                    6,
                    6,
                    6,
                    6,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [290] = new List<int>
                {
                    87,
                    65,
                    49,
                    43,
                    36,
                    29,
                    25,
                    20,
                    16,
                    12,
                    10,
                    9,
                    7,
                    7,
                    6,
                    6,
                    6,
                    6,
                    6,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
                [300] = new List<int>
                {
                    89,
                    66,
                    50,
                    44,
                    36,
                    30,
                    25,
                    20,
                    16,
                    13,
                    10,
                    9,
                    8,
                    8,
                    6,
                    6,
                    6,
                    6,
                    6,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    5,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                },
            };

        private readonly ILogger<PointsService> logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="PointsService"/> class.
        /// </summary>
        /// <param name="logger">Logger for this class.</param>
        public PointsService(ILogger<PointsService> logger)
        {
            this.logger = logger;
        }

        /// <summary>
        /// Calculate the number of points to award a player finishing in place
        /// <paramref name="place"/>, given that <paramref name="total"/> players participated.
        /// </summary>
        /// <param name="place">The finishing place to calculate points for.</param>
        /// <param name="total">The total number of players who participated in the session.</param>
        /// <returns>The number of points to award for the given finishing place.</returns>
        public int CalculatePoints(int place, int total)
        {
            using (this.logger.BeginScope($"Calculating points for place {place}/{total}."))
            {
                // Round the total number of players to the nearest 10.
                var roundedTotal =
                    (int)(Math.Round((decimal)total / 10, MidpointRounding.AwayFromZero) * 10);

                this.logger.LogInformation(
                    $"Rounded total number of places {total} to {roundedTotal}.");

                if (roundedTotal == 0)
                {
                    this.logger.LogWarning("Rounded total was 0, using 10.");
                    roundedTotal = 10;
                }
                else if (roundedTotal > 300)
                {
                    this.logger.LogWarning($"Rounded total was {roundedTotal}, using 300.");
                    roundedTotal = 300;
                }

                if (!Points.TryGetValue(roundedTotal, out var points))
                {
                    this.logger.LogError(
                        $"Tried to access points allocation list for total " +
                        $"{roundedTotal} that was not in the dictionary.");
                    return 0;
                }

                if (place > points.Count)
                {
                    this.logger.LogInformation(
                        $"Place {place} is outside bubble of size {points.Count} for " +
                        $"{total} total players.");
                    return 0;
                }

                return points[place - 1];
            }
        }
    }
}
